# Dracula
# https://draculatheme.com

background          = #282a36ea
search_background   = #44475a66
search_border       = #6272a4
search_text         = #f8f8f2
search_placeholder  = #6272a4
search_selection    = #bd93f973
app_label           = #f8f8f2
app_selected        = #44475a66
dot_active          = #f8f8f2
dot_inactive        = #6272a459
ai_idle             = #6272a4
ai_error            = #ff5555
ai_panel            = #21222c
ai_code_background  = #44475a
ai_code_text        = #f1fa8c
ai_link             = #8be9fd
terminal_background = #21222c
terminal_prompt     = #50fa7b
terminal_output     = #f8f8f2
button_background   = #44475a1a
copy_feedback       = #50fa7b
