# One Dark
# https://github.com/atom/atom/tree/master/packages/one-dark-syntax

background          = #282c34ea
search_background   = #2c313c66
search_border       = #3e4452
search_text         = #abb2bf
search_placeholder  = #5c6370
search_selection    = #61afef73
app_label           = #abb2bf
app_selected        = #2c313c66
dot_active          = #abb2bf
dot_inactive        = #5c637059
ai_idle             = #5c6370
ai_error            = #e06c75
ai_panel            = #21252b
ai_code_background  = #2c313c
ai_code_text        = #e5c07b
ai_link             = #61afef
terminal_background = #21252b
terminal_prompt     = #98c379
terminal_output     = #abb2bf
button_background   = #2c313c1a
copy_feedback       = #98c379
