# Rosé Pine
# https://rosepinetheme.com

background          = #191724ea
search_background   = #26233a66
search_border       = #6e6a86
search_text         = #e0def4
search_placeholder  = #6e6a86
search_selection    = #31748f73
app_label           = #e0def4
app_selected        = #26233a66
dot_active          = #e0def4
dot_inactive        = #6e6a8659
ai_idle             = #6e6a86
ai_error            = #eb6f92
ai_panel            = #21202e
ai_code_background  = #26233a
ai_code_text        = #f6c177
ai_link             = #9ccfd8
terminal_background = #21202e
terminal_prompt     = #9ccfd8
terminal_output     = #e0def4
button_background   = #26233a1a
copy_feedback       = #9ccfd8
