# Solarized Dark
# https://ethanschoonover.com/solarized

background          = #002b36ea
search_background   = #07364266
search_border       = #586e75
search_text         = #839496
search_placeholder  = #586e75
search_selection    = #268bd273
app_label           = #839496
app_selected        = #07364266
dot_active          = #839496
dot_inactive        = #586e7559
ai_idle             = #586e75
ai_error            = #dc322f
ai_panel            = #00212b
ai_code_background  = #073642
ai_code_text        = #b58900
ai_link             = #268bd2
terminal_background = #00212b
terminal_prompt     = #859900
terminal_output     = #93a1a1
button_background   = #0736421a
copy_feedback       = #859900
