# Tokyo Night
# https://github.com/folke/tokyonight.nvim

background          = #1a1b26ea
search_background   = #292e4266
search_border       = #565f89
search_text         = #c0caf5
search_placeholder  = #565f89
search_selection    = #7aa2f773
app_label           = #c0caf5
app_selected        = #292e4266
dot_active          = #c0caf5
dot_inactive        = #565f8959
ai_idle             = #565f89
ai_error            = #f7768e
ai_panel            = #16161e
ai_code_background  = #1f2335
ai_code_text        = #e0af68
ai_link             = #7aa2f7
terminal_background = #16161e
terminal_prompt     = #9ece6a
terminal_output     = #c0caf5
button_background   = #292e421a
copy_feedback       = #9ece6a
